# Matrics and Gradients

In [37]:
import numpy as np
import torch
import torchvision

In [38]:
X_train = np.array([[23, 32, 43, 343, 33, 44, 84, 34, 43, 423, 45, 56, 645, 254, 432],
           [344, 3454, 32, 656, 783, 645, 23, 57, 23, 775, 232, 757, 864, 85, 33],
           [23, 90, 233, 235, 907, 879, 402, 23, 44, 2323, 36, 232, 66, 232, 66],
           [239, 845, 323, 664, 64, 42, 98, 903, 886, 332, 64, 892, 34, 240, 89],
           [89, 23, 534, 134, 242, 53, 89, 775, 73, 353, 80, 489, 235, 24, 64]])

In [39]:
y = np.array([1, 2, 3, 2, 1])
y.shape

(5,)

In [40]:
X_test = np.array([[34, 89, 42, 24, 64, 23, 136, 643, 42, 633, 249, 24, 89, 23, 52],
                   [224, 646, 324, 89, 535, 64, 42, 64, 42, 646, 89, 909, 42, 53, 9],
                   [23, 456, 42, 646, 75, 24, 189, 53, 64, 89, 635, 89, 42, 63, 23],
                   [239, 845, 323, 664, 64, 42, 98, 903, 886, 332, 64, 892, 34, 240, 189]])

In [41]:
num_test = X_test.shape[0]
num_train = X_train.shape[0]

In [42]:
# 3 rows and 5 columns for all the X_train examples
dists = np.zeros((num_test, num_train))


In [43]:
for i in range(X_test.shape[0]):
    for j in range(X_train.shape[0]):
        
        dists[i, j] = np.sqrt(np.sum(np.square(X_test[i]-X_train[j])))

In [15]:
dists

array([[1036.22246646, 3773.82988488, 2229.08232239, 1677.37771536,
         812.01600969],
       [1475.85771672, 3073.00032541, 2149.96767418, 1467.34897008,
        1162.14672051],
       [1146.16447336, 3429.70844242, 2685.19422016, 1658.25812225,
        1354.37070258],
       [1869.79704781, 3198.32612471, 2865.74632513,  100.        ,
        1413.7298186 ]])

In [16]:
np.argsort(dists)
# dists.sort(key=lambda tup: tup[1])

array([[4, 0, 3, 2, 1],
       [4, 3, 0, 2, 1],
       [0, 4, 3, 2, 1],
       [3, 4, 0, 2, 1]], dtype=int64)

In [17]:
closest_y = []
for i in sorted_dists:
#     print(y[k][0])
    print(i)
    
#     print('y[k]:', y[k])
#     closest_y.ppend(y[k][0])
    

[4 0 3 2 1]
[4 3 0 2 1]
[0 4 3 2 1]
[3 4 0 2 1]


In [18]:
k = 1
closest_y = []
for i in range(k):
    closest_y.append(sorted_dists[i][0])
    
#     closest_y.append(y[sorted_dists[i]])
# closest_y.append(y[sorted_dists][k])


In [19]:
print(closest_y)

[4]


In [120]:
closest_y = []
for i in sorted_dists:
#     print(i)
    closest = i[0]
    closest_y.append(y[closest])
print(closest_y)

[1, 1, 1, 2]


In [128]:
# most common label in labels:
num_neighbors = X_train.shape[0]

In [129]:
num_neighbors

5

In [127]:
# closest_y = []
for i in range(num_test):
    closest_y = []
    sorted_dists = np.argsort(dists)
    print(closest)
    for i in range(sorted_dists):
#     print(i)
        closest = i[0]
        print(closest)
#         closest_y.append(y[closest])
#     y_pred[i] = max(set(closest_y), key=closest_y.count)
    
#     closest_y.append(sorted_dists[i][0])
    
    

3
4
4
0
3
3
4
4
0
3
3
4
4
0
3
3
4
4
0
3


In [114]:
closest_y

[4, 4, 0, 3]

In [57]:
minInRows = np.amin(dists, axis=1)

In [59]:
result = np.where(dists == np.amin(dists, axis=1))
print(result)

(array([], dtype=int64),)


<ipython-input-59-3b829d74b737>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  result = np.where(dists == np.amin(dists, axis=1))


In [62]:
dists

array([[4979.0437837 , 3772.16012385, 9623.92892742, 1678.09296524,
         812.38537653],
       [5029.83657786, 3073.00032541, 9596.99749922, 1467.34897008,
        1162.14672051],
       [4964.12459554, 3426.32456139, 9690.0396284 , 1655.78380231,
        1350.67390587]])

In [63]:
for i in dists:
    min_i = np.argmin(i, axis=0)
    print(min_i)

4
4
4


In [65]:
# predict_labels

# -dists: matrix of distances
# in dists: 1st image has the minimum distance at 812 so it should get the test label at 812.
# the 2nd image has min distance at 1162 and so, it should get the same distnace
# same is hte case for the third image 
# y_test = []
labels = []
for i in dists:
    # get the minimum
#     indices_dists = np.min(i)
    
    # get it's index 
    min_i = np.argmin(i, axis=0)
    labels.append(y[min_i])
    
#     min_index = np.where(dists == np.amin(dists, axis=1))
#     y_test.append(min_index[1])
#     y_test = list(zip(min_index[1]))
#     print(min_index)
#     print(type(min_index))
    print(labels)
    # get the indices first
    # then get the value for those form y by doing y[i]
#     y_test.append(y[i])
    # get the index of the mininum from the dists numpy and compare it with y array
#     y_test[i].append(np.min(i[]))

[1]
[1, 1]
[1, 1, 1]


In [51]:
arr == numpy.amin(arr)

812.3853765301293

In [37]:
y_test

[(4,)]

# Broadcasting

In [44]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 0.0],
              [1.8, 135.0,99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    0. ]
 [  1.8 135.   99.    0.9]]


In [86]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  68.9]


In [88]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 98.69375907]
 [ 2.03389831 43.51464435 33.46203346  0.        ]
 [ 3.05084746 56.48535565 63.70656371  1.30624093]]


In [89]:
# if only one dimension of a matrix and vector matches, Python will copy the vector to make it
# look like the same shape as the matrix and then, we add them elementwise.
# the row refers to test_point
# the column refers to training point
dists

array([[4979.0437837 , 3772.16012385, 9623.92892742, 1678.09296524,
         812.38537653],
       [5029.83657786, 3073.00032541, 9596.99749922, 1467.34897008,
        1162.14672051],
       [4964.12459554, 3426.32456139, 9690.0396284 , 1655.78380231,
        1350.67390587]])

In [90]:
dists.shape

(3, 5)

In [93]:
num_test = dists.shape[0]


In [94]:
y_pred = np.zeros(num_test)
print(y_pred)

[0. 0. 0.]


In [95]:
sorted_dist = np.argsort(dists)
print(sorted_dist)

[[4 3 1 0 2]
 [4 3 1 0 2]
 [4 3 1 0 2]]


In [102]:
for i in range(num_test):
    closest_y = []
    
    sorted_dists = np.argsort(dists)
    print(sorted_dists)
    print(sorted_dists[i][0])
    closest_y.append(sorted_dists[i][0])
    
    

[[4 3 1 0 2]
 [4 3 1 0 2]
 [4 3 1 0 2]]
4
[[4 3 1 0 2]
 [4 3 1 0 2]
 [4 3 1 0 2]]
4
[[4 3 1 0 2]
 [4 3 1 0 2]
 [4 3 1 0 2]]
4


In [103]:
closest_y

[4]

In [2]:
import numpy as np

In [68]:
X = np.array([[2, 3, 1, 2, 3, 2, 1, 3, 4, 4],
              [3, 3, 1, 2, 4, 5, 3, 5, 3, 2],
              [1, 2, 1, 3, 5, 4, 3, 4, 2, 1]])
W = np.array([[0.02, 0.01, 0.03],
              [0.04, 0.04, 0.03],
              [0.01, 0.05, 0.02],
              [0.05, 0.01, 0.01],
              [0.01, 0.09, 0.01],
              [0.02, 0.04, 0.02],
              [0.03, 0.01, 0.07],
              [0.01, 0.05, 0.02],
              [0.02, 0.06, 0.02],
              [0.01, 0.06, 0.04]])

scores= np.dot(X, W)
scores

array([[0.52, 1.2 , 0.63],
       [0.65, 1.36, 0.81],
       [0.57, 1.19, 0.64]])

In [74]:
scores.shape[0]

3

In [75]:
reg = 1

3

In [72]:
# scores for the correct classes
yi_scores = scores[np.arange(scores.shape[0]), y]

In [73]:
margins = np.maximum(0, (scores - np.matrix(yi_scores).T + 1))
margins

matrix([[0.32, 1.  , 0.43],
        [0.84, 1.55, 1.  ],
        [0.38, 1.  , 0.45]])

In [76]:
margins[np.arange(num_train), y] = 0

In [87]:
reg = 0.000005

In [88]:
loss = np.mean(np.sum(margins, axis=1))
loss += 0.5* reg * np.sum(W * W)

In [89]:
loss

1.0125000000000001e-07

In [90]:
binary = margins

binary[margins > 0] = 1
row_sum = np.sum(binary, axis=1)
binary[np.arange(num_train), y] = -row_sum.T

dW = np.dot(X.T, binary)

In [91]:
# Average
dW /= num_train 
dW += reg * W


In [92]:
dW

matrix([[2.0000001 , 1.00000005, 1.00000015],
        [2.66666687, 1.0000002 , 1.66666682],
        [1.00000005, 0.33333358, 0.66666677],
        [2.33333358, 0.66666672, 1.66666672],
        [4.00000005, 1.33333378, 2.66666672],
        [3.66666677, 1.66666687, 2.0000001 ],
        [2.33333348, 1.00000005, 1.33333368],
        [4.00000005, 1.66666692, 2.33333343],
        [3.0000001 , 1.0000003 , 2.0000001 ],
        [2.33333338, 0.66666697, 1.66666687]])

In [86]:
# since we only calculate the loss where the j is not equal to y_i


In [77]:
margins

matrix([[0.32, 0.  , 0.43],
        [0.84, 1.55, 0.  ],
        [0.38, 0.  , 0.45]])

In [49]:
y = np.array([1, 2, 1])


In [50]:
dW = np.zeros(W.shape)

In [65]:
dW = np.zeros(W.shape)
loss = 0.0
num_classes = W.shape[1]
num_train = X.shape[0]

scores = np.dot(X, W)
correct_class_score = scores[y]


In [66]:
scores[y]

array([[0.65, 1.36, 0.81],
       [0.57, 1.19, 0.64],
       [0.65, 1.36, 0.81]])

In [67]:
scores

array([[0.52, 1.2 , 0.63],
       [0.65, 1.36, 0.81],
       [0.57, 1.19, 0.64]])

In [61]:
margin = (scores - correct_scores + 1)

In [62]:
margin

array([[0.87, 0.84, 0.82],
       [1.08, 1.17, 1.17],
       [0.92, 0.83, 0.83]])

In [ ]:
for j in range(num_classes):
    margin = (scores[j] - correct_scores + 1)
    if margin.any() > 0:
        
    

In [51]:

# for i in range(X.shape[0]):
dW = np.zeros(W.shape)
loss = 0.0
num_classes = W.shape[1]
num_train = X.shape[0]
for i in range(num_train):
    scores = np.dot(X[i], W)
    correct_score = scores[y[i]]

    for j in range(num_classes):
        margin = (scores[j] - correct_score + 1)

        if margin > 0:
            loss += margin
            # for all the classes other than the y[i] classes, += X[i,:]
            dW[:, j] += X[i, :]
        
            dW[:, y[i]] -= X[i, :]
                

In [52]:
scores

array([0.57, 1.19, 0.64])

In [45]:
X = np.array([[2, 3, 1, 2, 3, 2, 1, 3, 4, 4],
              [3, 3, 1, 2, 4, 5, 3, 5, 3, 2],
              [1, 2, 1, 3, 5, 4, 3, 4, 2, 1]])

In [46]:
X

array([[2, 3, 1, 2, 3, 2, 1, 3, 4, 4],
       [3, 3, 1, 2, 4, 5, 3, 5, 3, 2],
       [1, 2, 1, 3, 5, 4, 3, 4, 2, 1]])

In [36]:
dW

array([[  6.,  -3.,  -3.],
       [  8.,  -7.,  -1.],
       [  3.,  -3.,   0.],
       [  7.,  -8.,   1.],
       [ 12., -12.,   0.],
       [ 11.,  -7.,  -4.],
       [  7.,  -5.,  -2.],
       [ 12.,  -9.,  -3.],
       [  9.,  -9.,   0.],
       [  7.,  -8.,   1.]])

In [24]:
dW

array([[ 6.,  6.,  6.],
       [ 8.,  8.,  8.],
       [ 3.,  3.,  3.],
       [ 7.,  7.,  7.],
       [12., 12., 12.],
       [11., 11., 11.],
       [ 7.,  7.,  7.],
       [12., 12., 12.],
       [ 9.,  9.,  9.],
       [ 7.,  7.,  7.]])

In [5]:
correct_class_score = scores[y]
correct_class_score

0.34

In [16]:
# that is the score for the correct class
# what we are trying to do is minimize the loss for that class
# so we are going to calculate the loss:
loss = 0.0
for j in range(3):
    if j == y:
        continue
    margin = (scores[j] - correct_class_score + 1)
    if margin >0:
        loss += margin
        
        dW[:, j] += X
        dW[:, y] -= X
        

In [17]:
dW

array([[ 4., -4.,  2.],
       [ 6., -6.,  3.],
       [ 8., -8.,  4.]])

In [7]:
margin

0.8899999999999999

In [9]:
margin

0.8899999999999999

In [10]:
print(loss)

1.75


In [12]:
dW = np.zeros(W.shape)

In [13]:
dW

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])